# This file is auto-generated by the notx-engine release-client-tap workflow.
# Do not edit it by hand — changes will be overwritten on the next client release.
cask "notx-desktop" do
  version "0.0.17"

  if Hardware::CPU.arm?
    url "https://github.com/zebaqui/notx-engine/releases/download/client-v0.0.17/notx-0.0.17-arm64.dmg"
    sha256 "3be8ad1e5d657fc31d941fcba1dbbbd908fdc07821fcb7c87da693348e110c17"
  end

  name "notx"
  desc "Electron client for the notx engine"
  homepage "https://github.com/zebaqui/notx"

  app "notx.app"

  zap trash: [
    "~/Library/Application Support/notx",
    "~/Library/Logs/notx",
    "~/Library/Preferences/com.zebaqui.notx.plist",
  ]
end
