# This file is auto-generated by the notx-engine release-client-tap workflow.
# Do not edit it by hand — changes will be overwritten on the next client release.
cask "notx-desktop" do
  version "0.0.23"

  url "https://github.com/zebaqui/notx-engine/releases/download/client-v0.0.23/notx-0.0.23-arm64.dmg"
  sha256 "89b47db5cfc2021df14cf5bdb623d62bdde22eebe8fdf8468c5f835729fac4b3"

  name "notx"
  desc "notx desktop — Electron client for the notx engine"
  homepage "https://github.com/zebaqui/notx"

  app "notx.app"

  zap trash: [
    "~/Library/Application Support/notx",
    "~/Library/Logs/notx",
    "~/Library/Preferences/com.zebaqui.notx.plist",
  ]
end
