# This file is auto-generated by the notx-engine release-client-tap workflow.
# Do not edit it by hand — changes will be overwritten on the next client release.
cask "notx-desktop" do
  version "0.0.25"

  url "https://github.com/zebaqui/notx-engine/releases/download/client-v0.0.25/notx-0.0.25-arm64.dmg"
  sha256 "1f36190dab87841db6dc0b6171b2eb95859874fc4d3ce73c19694a282cbff2fa"

  name "notx"
  desc "notx desktop — Electron client for the notx engine"
  homepage "https://github.com/zebaqui/notx"

  app "notx.app"

  zap trash: [
    "~/Library/Application Support/notx",
    "~/Library/Logs/notx",
    "~/Library/Preferences/com.zebaqui.notx.plist",
  ]
end
