# This file is auto-generated by the notx-engine release-client-tap workflow.
# Do not edit it by hand — changes will be overwritten on the next client release.
class NotxDesktop < Formula
  desc "notx desktop — Electron client for the notx engine"
  homepage "https://github.com/zebaqui/notx"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zebaqui/notx-engine/releases/download/client-v0.0.4/notx-v0.0.4-darwin-arm64.zip"
      sha256 "20a146b66ebe99f9520ac77f08bf3462183ba3899757e26df31e7bf41605746f"
    else
      url "https://github.com/zebaqui/notx-engine/releases/download/client-v0.0.4/notx-v0.0.4-darwin-amd64.zip"
      sha256 ""
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    app = "notx.app"
    prefix.install app
    bin.write_exec_script prefix / "#{app}/Contents/MacOS/notx"
  end

  test do
    assert_predicate prefix / "notx.app", :directory?
  end
end
