# This file is auto-generated by the notx release workflow.
# Do not edit it by hand — changes will be overwritten on the next release.
class Notx < Formula
  desc "notx — lightweight event-streaming / notification engine"
  homepage "https://github.com/zebaqui/notx-engine"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zebaqui/notx-engine/releases/download/v0.0.3/notx-v0.0.3-darwin-arm64.tar.gz"
      sha256 ""
    else
      url "https://github.com/zebaqui/notx-engine/releases/download/v0.0.3/notx-v0.0.3-darwin-amd64.tar.gz"
      sha256 "eb94741b9a0b3162d7ccfeb345da6d374a90d404f3c7a72581530edbf3c5d588"
    end
  end

  def install
    bin.install "notx-darwin-#{Hardware::CPU.arm? ? "arm64" : "amd64"}" => "notx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/notx version")
  end
end
