# This file is auto-generated by the notx-engine release-client-tap workflow.
# Do not edit it by hand — changes will be overwritten on the next client release.
class NotxDesktop < Formula
  desc "notx desktop — Electron client for the notx engine"
  homepage "https://github.com/zebaqui/notx"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zebaqui/notx-engine/releases/download/v0.0.3/notx-v0.0.3-darwin-arm64.zip"
      sha256 "a6a2775cdc166f4c7519d3eeca4925047c91706048453c2551a3bc0980ffa6ce"
    else
      url "https://github.com/zebaqui/notx-engine/releases/download/v0.0.3/notx-v0.0.3-darwin-amd64.zip"
      sha256 ""
    end
  end

  def install
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    app = "notx.app"
    prefix.install app
    bin.write_exec_script prefix / "#{app}/Contents/MacOS/notx"
  end

  test do
    assert_predicate prefix / "notx.app", :directory?
  end
end
