# This file is auto-generated by the notx-engine release-client-tap workflow.
# Do not edit it by hand — changes will be overwritten on the next client release.
class NotxDesktop < Formula
  desc "Electron client for the notx engine"
  homepage "https://github.com/zebaqui/notx"
  version "0.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zebaqui/notx-engine/releases/download/client-v0.0.17/notx-0.0.17-arm64-mac.zip"
      sha256 "0d4ca69025eab31def7d010b7dd956a4212e06280c1afd495dfa3ee82889d89a"
    end
  end

  def install
    app = "notx.app"
    prefix.install app
    bin.write_exec_script prefix / "#{app}/Contents/MacOS/notx"
  end

  test do
    assert_predicate prefix / "notx.app", :directory?
  end
end
