# This file is auto-generated by the notx release workflow.
# Do not edit it by hand — changes will be overwritten on the next release.
class Notx < Formula
  desc "notx — lightweight event-streaming / notification engine"
  homepage "https://github.com/zebaqui/notx-engine"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zebaqui/notx-engine/releases/download/v0.0.6/notx-v0.0.6-darwin-arm64.tar.gz"
      sha256 "7b243eb47d18473c23c792c541cca200ca2ef369c2f059baa718a4337dce406d"
    else
      url "https://github.com/zebaqui/notx-engine/releases/download/v0.0.6/notx-v0.0.6-darwin-amd64.tar.gz"
      sha256 ""
    end
  end

  def install
    bin.install "notx-darwin-#{Hardware::CPU.arm? ? "arm64" : "amd64"}" => "notx"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/notx version")
  end
end
